# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ce4668b14e15e37d02241070ce906e76f06c13d6095d598b26dd2d52a013480cfb43fa7d2783883a2f1308ce5b31055176e42f7538e4eda3cb84ebe05b5234

test:
  secret_key_base: 8bfa050b3e69ac3571b961eff46c48de4aeff1983fdbbf88cdf9ffdb823c14f13b8e81e72e3fc377aebba2e075c952a1ac7711f9b7aabc2e38d3c1ead61896fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
